"""Procedural, tileable skin micro-detail for the digital-human skin shader.

    python3 -I tools/inez/dh_skin_detail.py --out assets/characters/inez/textures/digital_human

Writes skin_micro_normal.png (RGBA): RGB = tangent-space normal (OpenGL
convention, +Y up, as glTF), A = height (0.5 = surface, darker = cavity).
One tile represents --tile-mm of skin (default 24 mm). The shader repeats it
across the head UVs at the measured scale: about 0.95 m per U unit and
0.48 m per V unit (median over the face primitive, see
docs/INEZ_SKIN_RENDERING.md), so the tile is repeated 40 x 20 times.

Content, all synthesised here (no scan data, no third-party texture):
- pores: Poisson-distributed shallow pits, radius 0.04-0.09 mm, density
  --pores-per-cm2 (default 60, within the 40-100 /cm^2 range reported for
  facial skin);
- skin relief: the fine criss-cross furrow network of the epidermis,
  modelled as band-limited noise stretched along two crossing directions
  (period about 0.3-0.8 mm);
- a faint isotropic roughness noise.

Every component is built in the frequency domain or with circular
convolution, so the tile is seamless. The normal is computed with periodic
central differences. Mipmaps are generated by the renderer, so the detail
averages out (and fades) at distance instead of aliasing.
"""
import argparse
import json
from pathlib import Path

import numpy as np
from PIL import Image


def band_noise(rng, n, low, high, aniso_angle=None, aniso=1.0):
    """Periodic noise with energy between spatial frequencies low..high (cycles per tile)."""
    f = np.fft.fftfreq(n)*n
    fx, fy = np.meshgrid(f, f, indexing='xy')
    if aniso_angle is not None:
        c, s = np.cos(aniso_angle), np.sin(aniso_angle)
        u, v = c*fx+s*fy, -s*fx+c*fy
        r = np.sqrt((u*aniso)**2+v**2)
    else:
        r = np.hypot(fx, fy)
    shape = np.exp(-((np.log(np.maximum(r, 1e-6))-np.log(np.sqrt(low*high)))**2)/(2*(np.log(high/low)/2.5)**2))
    shape[0, 0] = 0
    spectrum = np.fft.fft2(rng.standard_normal((n, n)))*shape
    out = np.real(np.fft.ifft2(spectrum))
    return out/np.std(out)


def pores(rng, n, tile_mm, per_cm2):
    count = int(round(per_cm2*(tile_mm/10)**2))
    texel_mm = tile_mm/n
    field = np.zeros((n, n))
    ys, xs = rng.integers(0, n, count), rng.integers(0, n, count)
    radii = rng.uniform(0.04, 0.09, count)/texel_mm
    depth = rng.uniform(0.6, 1.0, count)
    half = int(np.ceil(radii.max()*3))
    oy, ox = np.mgrid[-half:half+1, -half:half+1]
    for y, x, r, d in zip(ys, xs, radii, depth):
        blob = d*np.exp(-(ox**2+oy**2)/(2*r**2))
        field[np.ix_((y+np.arange(-half, half+1)) % n, (x+np.arange(-half, half+1)) % n)] += blob
    return field, count


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--out', required=True)
    parser.add_argument('--size', type=int, default=1024)
    parser.add_argument('--tile-mm', type=float, default=24.0)
    parser.add_argument('--pores-per-cm2', type=float, default=60.0)
    parser.add_argument('--seed', type=int, default=20261010)
    args = parser.parse_args()
    rng = np.random.default_rng(args.seed)
    n, tile = args.size, args.tile_mm
    cycles = lambda period_mm: tile/period_mm  # noqa: E731
    pore, count = pores(rng, n, tile, args.pores_per_cm2)
    relief = (band_noise(rng, n, cycles(0.8), cycles(0.3), np.radians(35), 3.0) +
              band_noise(rng, n, cycles(0.8), cycles(0.3), np.radians(-55), 3.0))
    relief = np.abs(relief)  # zero crossings become narrow furrows between plateaus
    fine = band_noise(rng, n, cycles(0.15), cycles(0.06))
    # Heights in micrometres: pores ~25 um deep, furrows ~15 um, fine noise ~3 um.
    height_um = -25*pore/max(pore.max(), 1e-6) + 15*(relief-relief.mean())/np.std(relief) + 3*fine
    texel_um = tile*1000/n
    gx = (np.roll(height_um, -1, 1)-np.roll(height_um, 1, 1))/(2*texel_um)
    gy = (np.roll(height_um, -1, 0)-np.roll(height_um, 1, 0))/(2*texel_um)
    # Image rows run downward; OpenGL tangent space has +V up, so dh/dv = -gy.
    nrm = np.dstack([-gx, gy, np.ones_like(gx)])
    nrm /= np.linalg.norm(nrm, axis=2, keepdims=True)
    h = height_um
    h01 = np.clip(0.5+h/(2*np.percentile(np.abs(h), 99.5)), 0, 1)
    rgba = np.dstack([(nrm*0.5+0.5), h01])
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    Image.fromarray(np.round(rgba*255).astype(np.uint8), 'RGBA').save(out/'skin_micro_normal.png', optimize=True)
    slope = np.degrees(np.arctan(np.hypot(gx, gy)))
    meta = {'file': 'skin_micro_normal.png', 'size': n, 'tile_mm': tile, 'texel_um': texel_um, 'pores': count,
            'pores_per_cm2': args.pores_per_cm2, 'seed': args.seed, 'slope_deg_p50_p99': [float(np.percentile(slope, 50)), float(np.percentile(slope, 99))],
            'height_um_p1_p99': [float(np.percentile(h, 1)), float(np.percentile(h, 99))],
            'licence': 'Project-owned: synthesised procedurally by tools/inez/dh_skin_detail.py'}
    (out/'skin_micro_normal.json').write_text(json.dumps(meta, indent=2)+'\n')
    print(json.dumps(meta))


if __name__ == '__main__':
    main()
