"""Retain explicit single-view built-in ImageGen requests. This script does not call a generator."""
from pathlib import Path
import argparse,json

ROOT=Path('/workspace/assets/characters/inez')
LOCK='''Faithfully reconstruct ONE separate view of INEZ, the SAME adult woman in the attached original images. This is reconstruction, never character redesign. Original A (two portraits) has final authority for facial identity; original B (front/rear body and face) has final authority for body/costume. Any attached approved generated views are supplemental consistency guides; originals override them. Never use generated guides as sole identity evidence. Preserve original facial proportions: elongated slightly hooded green-hazel eyes, natural original eye size and spacing, substantial softly rounded nose tip/alar width, full but natural lips with fuller lower lip and slightly irregular Cupid's bow, soft cheek volumes and rounded substantial chin/lower face. No narrow nose, pointed chin, larger eyes, glamour retouch or makeup. Preserve the uneven source freckles (restrained forehead density), pores, warm-neutral real skin and subtle red/brown variation. Medium-brown untidy wavy/curly hair in loose high ponytail, lifted crown and asymmetric forehead/temple curls to jaw/neck. No sleek hair, bun, braid or alternative hairstyle. Keep body silhouette moderate and original, no slimming or exaggerated anatomy. Costume remains roomy cropped charcoal-gray coarse knit crew-neck sweater with THREE broad very dark navy/charcoal torso stripes and wider gray intervals, gray ribbed collar/cuffs/hem and roomy long sleeves; loose high-waist washed nearly black jeans, no belt; black tall lace-up rounded-toe thick-platform combat boots with subdued black hardware/seams and continuous black soles, absolutely NO yellow/tan welt stitching, branding or buckles; very fine silver necklace with original tiny irregular pointed pendant, no enlarged or newly symbolic charm. Exact hidden profile geometry and tiny pendant motif are not known from originals; make conservative internally consistent proposals, not decorative invented detail. All views: consistent soft neutral studio lighting, uniform light-gray seamless background, photoreal physically plausible anatomy/materials, orthographic or 100mm long-lens perspective, sharp clear surfaces without strong depth-of-field, no dramatic acting or poses, no beauty filters, stylization, inset, labels, collage, sheet or watermark. ONE view only.'''

VIEWS={
'02_face_left_profile':'''TRUE anatomical LEFT-side 90-degree profile portrait. Nose points toward IMAGE LEFT. Camera exactly at eye height on character's left, face entirely side-on, near eye visible and far eye hidden naturally (not a three-quarter face). The nose/philtrum/lips/chin/forehead form one coherent sagittal silhouette matching the approved front geometry and A's oblique proportions. Preserve the broad softly rounded original nose rather than inventing a sharply upturned or delicate tip. Neutral relaxed brows/gaze and resting closed mouth. Keep whole crown, head, visible ear region, ponytail projection, neck, shoulders and upper chest in frame. Ponytail is high and full, curly, irregularly tapered to upper/mid-back as original B. No cut crown or hair tips. This is a conservative inferred profile; source A contains no true profile.''' ,
'03_face_right_profile':'''TRUE anatomical RIGHT-side 90-degree profile portrait. Nose points toward IMAGE RIGHT. Camera exactly on character's right at eye height, near eye visible and far eye naturally occluded, not three-quarter. Keep head silhouette, nose projection, lip volumes and chin consistent with approved front and opposite profile; do not mirror a previous image, because face-framing curls and source asymmetries must remain plausible from this actual opposite camera side. Preserve substantial rounded source nose, original eyelid aperture, full lower lip, rounded chin and natural neck. Neutral relaxed expression. Entire crown/head/ponytail/neck and shoulders/upper chest with necklace inside frame. High curly ponytail matches B rear silhouette. No cropped hair. Profile geometry remains inferred, not a recovered original side photograph.''',
'04_face_three_quarter':'''Neutral portrait at approximately 45 degrees, viewing the anatomical left side and nose pointing IMAGE LEFT. Turn the head/body naturally to expose true three-quarter geometry while keeping eye line level, both eyes appropriately foreshortened, forward gaze along the head axis and relaxed brows/closed resting mouth. Match original A's left portrait likeness closely, but use the requested neutral studio lighting and gray background. Preserve original nose width and rounded projection, cheek volume, jaw and chin, natural lips, eyelids and asymmetrical curls. Entire crown, full head, ponytail, neck, shoulders and upper chest visible. Do not copy the tension/expression of A as anatomy.''',
'06_body_side':'''One complete head-to-toe TRUE anatomical LEFT SIDE (90 degrees), nose points IMAGE LEFT, minimal orthographic distortion. Same original proportions, neutral shallow A-pose, outfit, stance, arm/leg lengths and scale as accepted front body. Use the SAME portrait canvas/body scale with about 2-3% top margin and 4-5% bottom margin; full crown, ponytail, all naturally visible fingers and complete boot soles in frame. Hidden far limbs may be naturally occluded, never missing/truncated. Relaxed level head and forward gaze, no contrapposto or fashion pose. Side silhouette must show coherent forehead/nose/lips/chin, natural chest/abdomen/back and jean volume without an invented exaggerated bust or narrowed waist. Accurate ponytail projection from high rear attachment with dense irregular curls ending on upper/mid-back, no bun. Maintain cropped hem/small midriff, ribbed cuffs, stripe continuity around sleeve/torso, roomy jeans gathered at boot tops, and thick flat black platform combat boot profile. Side body depth is a conservative reconstruction, not directly measured original geometry.''',
'07_body_back':'''One complete head-to-toe true REAR view in the SAME neutral shallow A-pose, original body proportions/scale and same stance as approved front. Copy original B's rear silhouette, sweater stripe phases/construction, high curly ponytail ending upper/mid-back, rear waistband, two rear patch pockets and loose jean folds/gathers, and black combat platform boot heels/soles. The ponytail must remain irregular dense curly hair, not a braid, straight tube or bun. Neck and upper hairline natural; no headless artifact. Slightly separated straight arms, hands with intact anatomy, both boots complete, entire crown and ponytail inside frame. Same portrait canvas/body scale as front, about 2-3% top margin and 4-5% bottom margin. No face looking back, twist, missing arms or cropped hands/feet. Necklace chain may only show what is physically visible at back neck, no pendant moved to back.''',
'08_eyes_closeup':'''High-detail closeup of BOTH of Inez's actual eyes together, eyebrows, eyelid folds, inner/outer corners and upper nose bridge. Preserve original horizontal eye shape/spacing and restrained upper-lid hooding rather than attractive enlarged round eyes. Green-hazel muted olive/gray-green irises with warmer central variation, real pupils/limbal transitions, natural lashes, subtle tearline/corneal highlights, original skin/freckles and under-eye shading. Neutral resting brow/gaze, no fear or makeup. Sharp macro-scale material reference with physically plausible lighting, not a redesigned isolated generic eyeball. Preserve the reference's normal eye aperture; no circle-light glamour reflections.''',
'09_lips_closeup':'''High-detail natural closeup of Inez's lower nose, philtrum, complete lips, mouth corners, chin and nearby skin in a true frontal neutral resting expression. Original moderately full lip geometry, lower lip fuller, restrained slightly irregular Cupid's bow, natural muted rose/brown color, fine vertical lip lines and subtle surface roughness. Preserve exact mouth width and relationship to substantial rounded nose and rounded chin. No lip fillers, lipstick, over-glossing or newly perfect symmetric lip shape; no visible new teeth. Source freckles/skin variation remain. This is one crop of SAME identity, not independent beauty lips.''',
'10_skin_freckles_closeup':'''High-detail closeup across Inez's nose bridge and both cheeks, enough eye/mouth context to locate the skin. Faithful source freckle cluster distribution: uneven natural cheek/nose freckles and muted brown/red tonal marks, restrained forehead marks if forehead is visible, not an evenly repeated dotted mask. Visible fine pores and micro roughness, subtle cheek redness and under-eye tonal variation, realistic tiny specular response. No smoothing, oily glitter, harsh acne exaggeration or arbitrary new large moles. Neutral even light, crisp skin surface rather than strongly sharpened procedural texture. Original marks at available source resolution have final authority; newly resolved subpixel microdetail is reconstruction, not proven exact placement.''',
'11_necklace_closeup':'''High-detail crop of Inez's neck base, original crew neck knit collar, fine silver chain and original VERY SMALL pendant against the striped upper chest. Preserve the chain's fine thickness, modest shallow V drape, original upper-chest placement and pendant's tiny proportion to neckline. Visible pendant silhouette is an irregular small branched/pointed silver detail; motif cannot be resolved from original pixels. Do NOT invent a larger cross/star/bird/flower, gemstone, medallion, oversized bail or extra chain. Reproduce only visible silhouette/material evidence conservatively. Do not make the pendant enormous to show detail. Include full necklace extent, chest stripe and collar to judge scale. Neutral studio material reference.''',
'12_sweater_material_closeup':'''High-detail garment crop from neck/collar through the cropped sweater hem and both upper sleeves, showing the source THREE broad dark navy/charcoal horizontal torso stripes separated by wider charcoal-gray knit intervals, upper gray shoulder area, ribbed gray crew collar and ribbed gray hem/cuffs where visible. Preserve exact original stripe order/phase and garment roomy/drop-shoulder construction. Visible coarse knit stitches, matte soft fiber detail, cloth thickness, subdued realistic roughness, natural shallow folds and seams; not a smooth shirt with painted bands, cable-knit redesign or fuzzy fur. Keep original charcoal/gray/dark-navy subdued colors. Fine original necklace may appear without any new jewelry. No face required in this material crop.''',
'13_boots_closeup':'''High-detail closeup of BOTH of Inez's worn black lace-up combat/platform boots and the gathered lower jeans, showing complete toes, tall ankle uppers, all laces/eyelets and entire thick soles with ample margin. Camera modest front three-quarter/near-front to show sole depth without perspective stretching. Exact source black leather-like panel behavior, subdued black seams/hardware, black laces, restrained leather highlights, thick continuous flat black platform sole and original rounded toe proportion. Absolutely no yellow/tan/ochre stitching or trim, branding, heel, buckle or new oversized tread/metal decoration. Do not shrink platforms or invent unseen bottom-tread patterns; inspect B's visible construction. Both full boots clear, no foot crop. Same dark loose jeans bunch at boot tops. Neutral gray studio material reference.'''
}

def main():
 p=argparse.ArgumentParser();p.add_argument('view',choices=VIEWS);p.add_argument('--version',type=int,default=1);a=p.parse_args()
 anchors=[str(ROOT/'references/original/inez_portraits.jpg'),str(ROOT/'references/original/inez_turnaround.jpg')]
 guides=['05_body_front'] if a.view=='06_body_side' else ['01_face_front_neutral','05_body_front']
 if a.view in ['03_face_right_profile','04_face_three_quarter','06_body_side']:
  guides.append('02_face_left_profile')
 for guide in guides:
  path=ROOT/'references/approved'/(guide+'.png')
  if path.exists():anchors.append(str(path))
 if a.view in ['06_body_side','07_body_back']:
  boots=ROOT/'references/approved/13_boots_closeup.png'
  if boots.exists():anchors.append(str(boots))
 if len(anchors)>5:
  raise ValueError('Built-in ImageGen supports at most five image anchors; never drop the two originals.')
 prompt=LOCK+'\n\nREQUESTED VIEW: '+VIEWS[a.view]
 if (ROOT/'references/approved/05_body_front.scope.json').exists():
  prompt+='\n\nSUPPLEMENTARY GUIDE SCOPE: Any attached 05_body_front is approved ONLY for whole-body geometry, neutral A-pose and silhouette. Its warm boot stitching and denim wash/microtexture are rejected and MUST NOT propagate. Original B governs denim and costume; attached approved boots guide (if present) supports neutral black seams only.'
 if a.view in ['03_face_right_profile','04_face_three_quarter','06_body_side']:
  prompt+='\n\nPROFILE GUIDE SCOPE: Attached approved left profile supports coherent conservative face silhouette only. Its ponytail appears too long; DO NOT copy its tail length. Original B rear ponytail reaches the upper-back stripe region and remains the final hair-length/volume authority. For true right/side views, far eye/far lashes must naturally occlude at 90 degrees.'
 target=ROOT/'qa/prompts'/(a.view+'_v%02d'%a.version)
 target.with_suffix('.txt').write_text(prompt+'\n')
 target.with_suffix('.request.json').write_text(json.dumps(dict(prompt=prompt,referenced_image_paths=anchors,transparent_background=False),indent=2)+'\n')
 print(str(target.with_suffix('.request.json')))
if __name__=='__main__':main()
